In [1]:
import numpy as np
matrix = np.matrix(
    [[0.9, 0.075, 0.025], [0.15, 0.8, 0.05], [0.25, 0.25, 0.5]], dtype=float
)
vector1 = np.matrix([[0.3, 0.4, 0.3]], dtype=float)

for i in range(100):
    vector1 = vector1 * matrix
    print("Courrent round: {}".format(i + 1))
    print(vector1)

Courrent round: 1
[[0.405  0.4175 0.1775]]
Courrent round: 2
[[0.4715  0.40875 0.11975]]
Courrent round: 3
[[0.5156 0.3923 0.0921]]
Courrent round: 4
[[0.54591  0.375535 0.078555]]
Courrent round: 5
[[0.567288 0.36101  0.071702]]
Courrent round: 6
[[0.5826362 0.3492801 0.0680837]]
Courrent round: 7
[[0.59378552 0.34014272 0.06607176]]
Courrent round: 8
[[0.60194632 0.33316603 0.06488765]]
Courrent round: 9
[[0.6079485  0.32790071 0.06415079]]
Courrent round: 10
[[0.61237646 0.3239544  0.06366914]]
Courrent round: 11
[[0.61564926 0.32100904 0.0633417 ]]
Courrent round: 12
[[0.61807111 0.31881635 0.06311253]]
Courrent round: 13
[[0.61986459 0.31718655 0.06294886]]
Courrent round: 14
[[0.62119333 0.3159763  0.06283037]]
Courrent round: 15
[[0.62217803 0.31507813 0.06274383]]
Courrent round: 16
[[0.62290791 0.31441182 0.06268027]]
Courrent round: 17
[[0.62344896 0.31391762 0.06263343]]
Courrent round: 18
[[0.62385006 0.31355112 0.06259882]]
Courrent round: 19
[[0.62414743 0.31327936 0.0625